#define CODCMD_MOSTRAR_TOPO_RED 1 //Mostrar topología
#define CODCMD_MOSTRAR_NODO 2
#define CODCMD_MOSTRAR_ARP 3
#define CODCMD_MOSTRAR_MAC 4
#define CODCMD_MOSTRAR_TABLA_RUTEO 5
#define CODCMD_RESOLVER_ARP 13
#define CODCMD_AGREGAR_RUTA 16
